root - INFO - Бот запускается
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002A8B0A63248>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')': /bot1038450751:AAGhpHSE0iAXJVTnq1VA26BHZ6nE1P7B2Kg/getMe
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002A8B0A63888>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')': /bot1038450751:AAGhpHSE0iAXJVTnq1VA26BHZ6nE1P7B2Kg/getMe
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002A8B0A63988>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')': /bot1038450751:AAGhpHSE0iAXJVTnq1VA26BHZ6nE1P7B2Kg/getMe
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000019CF46D8F48>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')': /bot1038450751:AAGhpHSE0iAXJVTnq1VA26BHZ6nE1P7B2Kg/getMe
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000019CF46E47C8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')': /bot1038450751:AAGhpHSE0iAXJVTnq1VA26BHZ6nE1P7B2Kg/getMe
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000019CF46E4808>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')': /bot1038450751:AAGhpHSE0iAXJVTnq1VA26BHZ6nE1P7B2Kg/getMe
2019-11-29 19:43:41,581 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000018275179EC8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')': /bot1038450751:AAGhpHSE0iAXJVTnq1VA26BHZ6nE1P7B2Kg/getMe
2019-11-29 19:43:41,815 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000018275188508>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')': /bot1038450751:AAGhpHSE0iAXJVTnq1VA26BHZ6nE1P7B2Kg/getMe
2019-11-29 19:43:42,066 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000018275188648>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')': /bot1038450751:AAGhpHSE0iAXJVTnq1VA26BHZ6nE1P7B2Kg/getMe
2019-11-29 19:44:29,696 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000201F4919E08>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')': /bot1038450751:AAGhpHSE0iAXJVTnq1VA26BHZ6nE1P7B2Kg/getMe
2019-11-29 19:44:29,902 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000201F49284C8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')': /bot1038450751:AAGhpHSE0iAXJVTnq1VA26BHZ6nE1P7B2Kg/getMe
2019-11-29 19:44:30,108 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000201F4928608>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')': /bot1038450751:AAGhpHSE0iAXJVTnq1VA26BHZ6nE1P7B2Kg/getMe
